<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>fftStage</name>
      <module_structure>Dataflow</module_structure>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>p_fftInData_reOrdered</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName>FIFO_LUTRAM</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>53</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>128</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>p_fftOutData_0_0_0_0_0</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName>FIFO</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>0</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_3">
          <Value>
            <Obj>
              <type>1</type>
              <id>3</id>
              <name>p_fftOutData_0_0_0_0_01</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName>FIFO</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>53</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_4">
          <Value>
            <Obj>
              <type>1</type>
              <id>4</id>
              <name>p_fftOutData_0_1_0_0_0</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName>FIFO</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>53</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_5">
          <Value>
            <Obj>
              <type>1</type>
              <id>5</id>
              <name>p_fftOutData_0_1_0_0_02</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName>FIFO</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1685024095</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>56</id>
              <name>fftOutData_local</name>
              <fileName>../fixed/vitis_fft/hls_ssr_fft.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>885</lineNumber>
              <contextFuncName>fftStage</contextFuncName>
              <contextNormFuncName>fftStage</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>/mnt/HLSNAS/g110064539/composable_IP_file/FFT_src/fft</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>../fixed/vitis_fft/hls_ssr_fft.hpp</first>
                        <second>fftStage</second>
                      </first>
                      <second>885</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>fftOutData_local</originalName>
              <rtlName>fftOutData_local_U</rtlName>
              <control>pragma</control>
              <opType>fifo</opType>
              <implIndex>lutram</implIndex>
              <coreName>FIFO_LUTRAM</coreName>
              <isStorage>1</isStorage>
              <storageDepth>8</storageDepth>
              <coreId>80</coreId>
              <rtlModuleName>fft_top1_fifo_w128_d8_D_x7</rtlModuleName>
            </Obj>
            <bitwidth>128</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>70</item>
          </oprand_edges>
          <opcode>alloca</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>60</id>
              <name>fftOutData_local2</name>
              <fileName>../fixed/vitis_fft/hls_ssr_fft.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>891</lineNumber>
              <contextFuncName>fftStage</contextFuncName>
              <contextNormFuncName>fftStage</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/HLSNAS/g110064539/composable_IP_file/FFT_src/fft</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../fixed/vitis_fft/hls_ssr_fft.hpp</first>
                        <second>fftStage</second>
                      </first>
                      <second>891</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>fftOutData_local2</originalName>
              <rtlName>fftOutData_local2_U</rtlName>
              <control>pragma</control>
              <opType>fifo</opType>
              <implIndex>lutram</implIndex>
              <coreName>FIFO_LUTRAM</coreName>
              <isStorage>1</isStorage>
              <storageDepth>8</storageDepth>
              <coreId>80</coreId>
              <rtlModuleName>fft_top1_fifo_w128_d8_D_x7</rtlModuleName>
            </Obj>
            <bitwidth>128</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>71</item>
          </oprand_edges>
          <opcode>alloca</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>64</id>
              <name>_ln897</name>
              <fileName>../fixed/vitis_fft/hls_ssr_fft.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>897</lineNumber>
              <contextFuncName>fftStage</contextFuncName>
              <contextNormFuncName>fftStage</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/HLSNAS/g110064539/composable_IP_file/FFT_src/fft</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../fixed/vitis_fft/hls_ssr_fft.hpp</first>
                        <second>fftStage</second>
                      </first>
                      <second>897</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_U0</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1767994478</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>73</item>
            <item>74</item>
            <item>75</item>
            <item>87</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>3</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>65</id>
              <name>_ln905</name>
              <fileName>../fixed/vitis_fft/hls_ssr_fft.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>905</lineNumber>
              <contextFuncName>fftStage</contextFuncName>
              <contextNormFuncName>fftStage</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/HLSNAS/g110064539/composable_IP_file/FFT_src/fft</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../fixed/vitis_fft/hls_ssr_fft.hpp</first>
                        <second>fftStage</second>
                      </first>
                      <second>905</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_U0</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1767994478</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>14</count>
            <item_version>0</item_version>
            <item>77</item>
            <item>78</item>
            <item>79</item>
            <item>88</item>
            <item>89</item>
            <item>90</item>
            <item>91</item>
            <item>92</item>
            <item>93</item>
            <item>94</item>
            <item>95</item>
            <item>306</item>
            <item>308</item>
            <item>309</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>4</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>66</id>
              <name>_ln906</name>
              <fileName>../fixed/vitis_fft/hls_ssr_fft.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>906</lineNumber>
              <contextFuncName>fftStage</contextFuncName>
              <contextNormFuncName>fftStage</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/HLSNAS/g110064539/composable_IP_file/FFT_src/fft</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../fixed/vitis_fft/hls_ssr_fft.hpp</first>
                        <second>fftStage</second>
                      </first>
                      <second>906</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>fftStage_1_U0</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1767994478</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>43</count>
            <item_version>0</item_version>
            <item>81</item>
            <item>82</item>
            <item>83</item>
            <item>84</item>
            <item>85</item>
            <item>86</item>
            <item>96</item>
            <item>97</item>
            <item>98</item>
            <item>99</item>
            <item>100</item>
            <item>101</item>
            <item>102</item>
            <item>103</item>
            <item>104</item>
            <item>105</item>
            <item>106</item>
            <item>107</item>
            <item>108</item>
            <item>109</item>
            <item>110</item>
            <item>111</item>
            <item>112</item>
            <item>113</item>
            <item>114</item>
            <item>115</item>
            <item>116</item>
            <item>117</item>
            <item>118</item>
            <item>119</item>
            <item>120</item>
            <item>121</item>
            <item>122</item>
            <item>123</item>
            <item>124</item>
            <item>125</item>
            <item>126</item>
            <item>127</item>
            <item>128</item>
            <item>129</item>
            <item>305</item>
            <item>307</item>
            <item>310</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>5</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>67</id>
              <name>_ln909</name>
              <fileName>../fixed/vitis_fft/hls_ssr_fft.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>909</lineNumber>
              <contextFuncName>fftStage</contextFuncName>
              <contextNormFuncName>fftStage</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/HLSNAS/g110064539/composable_IP_file/FFT_src/fft</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../fixed/vitis_fft/hls_ssr_fft.hpp</first>
                        <second>fftStage</second>
                      </first>
                      <second>909</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>909196388</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>6</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_12">
          <Value>
            <Obj>
              <type>2</type>
              <id>69</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>2352236016</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>64</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_13">
          <Value>
            <Obj>
              <type>2</type>
              <id>72</id>
              <name>fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_s</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>2353140480</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:fftStageKernelS2S&lt;64, 2, 1, 0, 0, 6, complex&lt;ap_fixed&lt;24, 9, 5, 3, 0&gt; &gt;, complex&lt;ap_fixed&lt;16, 3, 5, 3, 0&gt; &gt;, complex&lt;ap_fixed&lt;16, 3, 5, 3, 0&gt; &gt;, complex&lt;ap_fixed&lt;22, 7, 5, 3, 0&gt; &gt;, complex&lt;ap_fixed&lt;24, 9, 5, 3, 0&gt; &gt; &gt;&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_14">
          <Value>
            <Obj>
              <type>2</type>
              <id>76</id>
              <name>streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_s</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1902080097</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:streamingDataCommutor&lt;complex&lt;ap_fixed&lt;24, 9, 5, 3, 0&gt; &gt; &gt;&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_15">
          <Value>
            <Obj>
              <type>2</type>
              <id>80</id>
              <name>fftStage_1</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>2550015600</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:fftStage.1&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_16">
          <Obj>
            <type>3</type>
            <id>68</id>
            <name>fftStage</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <contextNormFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <control/>
            <opType/>
            <implIndex/>
            <coreName/>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>4294967295</coreId>
            <rtlModuleName/>
          </Obj>
          <node_objs>
            <count>6</count>
            <item_version>0</item_version>
            <item>56</item>
            <item>60</item>
            <item>64</item>
            <item>65</item>
            <item>66</item>
            <item>67</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>63</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_17">
          <id>70</id>
          <edge_type>1</edge_type>
          <source_obj>69</source_obj>
          <sink_obj>56</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_18">
          <id>71</id>
          <edge_type>1</edge_type>
          <source_obj>69</source_obj>
          <sink_obj>60</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_19">
          <id>73</id>
          <edge_type>1</edge_type>
          <source_obj>72</source_obj>
          <sink_obj>64</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_20">
          <id>74</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>64</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_21">
          <id>75</id>
          <edge_type>1</edge_type>
          <source_obj>56</source_obj>
          <sink_obj>64</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_22">
          <id>77</id>
          <edge_type>1</edge_type>
          <source_obj>76</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_23">
          <id>78</id>
          <edge_type>1</edge_type>
          <source_obj>56</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_24">
          <id>79</id>
          <edge_type>1</edge_type>
          <source_obj>60</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>81</id>
          <edge_type>1</edge_type>
          <source_obj>80</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>82</id>
          <edge_type>1</edge_type>
          <source_obj>60</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>83</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>84</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>85</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>86</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>87</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>64</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>88</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>89</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>90</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>91</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>92</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>93</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>94</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>95</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>96</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>97</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>98</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>99</id>
          <edge_type>1</edge_type>
          <source_obj>18</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>100</id>
          <edge_type>1</edge_type>
          <source_obj>19</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>101</id>
          <edge_type>1</edge_type>
          <source_obj>20</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>102</id>
          <edge_type>1</edge_type>
          <source_obj>21</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>103</id>
          <edge_type>1</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>104</id>
          <edge_type>1</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>105</id>
          <edge_type>1</edge_type>
          <source_obj>24</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>106</id>
          <edge_type>1</edge_type>
          <source_obj>25</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>107</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>108</id>
          <edge_type>1</edge_type>
          <source_obj>27</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>109</id>
          <edge_type>1</edge_type>
          <source_obj>28</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>110</id>
          <edge_type>1</edge_type>
          <source_obj>29</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>111</id>
          <edge_type>1</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>112</id>
          <edge_type>1</edge_type>
          <source_obj>31</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>113</id>
          <edge_type>1</edge_type>
          <source_obj>32</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>114</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>115</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>116</id>
          <edge_type>1</edge_type>
          <source_obj>35</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>117</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>118</id>
          <edge_type>1</edge_type>
          <source_obj>37</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>119</id>
          <edge_type>1</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>120</id>
          <edge_type>1</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>121</id>
          <edge_type>1</edge_type>
          <source_obj>40</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_66">
          <id>122</id>
          <edge_type>1</edge_type>
          <source_obj>41</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_67">
          <id>123</id>
          <edge_type>1</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_68">
          <id>124</id>
          <edge_type>1</edge_type>
          <source_obj>43</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_69">
          <id>125</id>
          <edge_type>1</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_70">
          <id>126</id>
          <edge_type>1</edge_type>
          <source_obj>45</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_71">
          <id>127</id>
          <edge_type>1</edge_type>
          <source_obj>46</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_72">
          <id>128</id>
          <edge_type>1</edge_type>
          <source_obj>47</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_73">
          <id>129</id>
          <edge_type>1</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_74">
          <id>305</id>
          <edge_type>4</edge_type>
          <source_obj>65</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_75">
          <id>306</id>
          <edge_type>4</edge_type>
          <source_obj>64</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_76">
          <id>307</id>
          <edge_type>4</edge_type>
          <source_obj>65</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_77">
          <id>308</id>
          <edge_type>4</edge_type>
          <source_obj>64</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_78">
          <id>309</id>
          <edge_type>4</edge_type>
          <source_obj>64</source_obj>
          <sink_obj>65</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_79">
          <id>310</id>
          <edge_type>4</edge_type>
          <source_obj>65</source_obj>
          <sink_obj>66</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_80">
        <mId>1</mId>
        <mTag>fftStage</mTag>
        <mNormTag>fftStage</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>68</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>-1</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>1</mIsDfPipe>
        <mDfPipe class_id="23" tracking_level="1" version="0" object_id="_81">
          <port_list class_id="24" tracking_level="0" version="0">
            <count>5</count>
            <item_version>0</item_version>
            <item class_id="25" tracking_level="1" version="0" object_id="_82">
              <name>p_fftInData_reOrdered</name>
              <dir>0</dir>
              <type>0</type>
              <need_hs>0</need_hs>
              <top_port class_id="-1"/>
              <chan class_id="-1"/>
            </item>
            <item class_id_reference="25" object_id="_83">
              <name>p_fftOutData_0_0_0_0_0</name>
              <dir>1</dir>
              <type>0</type>
              <need_hs>0</need_hs>
              <top_port class_id="-1"/>
              <chan class_id="-1"/>
            </item>
            <item class_id_reference="25" object_id="_84">
              <name>p_fftOutData_0_0_0_0_01</name>
              <dir>1</dir>
              <type>0</type>
              <need_hs>0</need_hs>
              <top_port class_id="-1"/>
              <chan class_id="-1"/>
            </item>
            <item class_id_reference="25" object_id="_85">
              <name>p_fftOutData_0_1_0_0_0</name>
              <dir>1</dir>
              <type>0</type>
              <need_hs>0</need_hs>
              <top_port class_id="-1"/>
              <chan class_id="-1"/>
            </item>
            <item class_id_reference="25" object_id="_86">
              <name>p_fftOutData_0_1_0_0_02</name>
              <dir>1</dir>
              <type>0</type>
              <need_hs>0</need_hs>
              <top_port class_id="-1"/>
              <chan class_id="-1"/>
            </item>
          </port_list>
          <process_list class_id="27" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_87">
              <type>0</type>
              <name>fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_U0</name>
              <ssdmobj_id>64</ssdmobj_id>
              <pins class_id="29" tracking_level="0" version="0">
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="30" tracking_level="1" version="0" object_id="_88">
                  <port class_id_reference="25" object_id="_89">
                    <name>p_fftInData_reOrdered</name>
                    <dir>0</dir>
                    <type>0</type>
                    <need_hs>0</need_hs>
                    <top_port class_id_reference="25" object_id_reference="_82"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id="31" tracking_level="1" version="0" object_id="_90">
                    <type>0</type>
                    <name>fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_U0</name>
                    <ssdmobj_id>64</ssdmobj_id>
                  </inst>
                </item>
              </pins>
              <in_source_fork>1</in_source_fork>
              <in_sink_join>0</in_sink_join>
              <flag_in_gui>0</flag_in_gui>
            </item>
            <item class_id_reference="28" object_id="_91">
              <type>0</type>
              <name>streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_U0</name>
              <ssdmobj_id>65</ssdmobj_id>
              <pins>
                <count>0</count>
                <item_version>0</item_version>
              </pins>
              <in_source_fork>0</in_source_fork>
              <in_sink_join>0</in_sink_join>
              <flag_in_gui>0</flag_in_gui>
            </item>
            <item class_id_reference="28" object_id="_92">
              <type>0</type>
              <name>fftStage_1_U0</name>
              <ssdmobj_id>66</ssdmobj_id>
              <pins>
                <count>4</count>
                <item_version>0</item_version>
                <item class_id_reference="30" object_id="_93">
                  <port class_id_reference="25" object_id="_94">
                    <name>p_fftOutData_0_0_0_0_0</name>
                    <dir>1</dir>
                    <type>0</type>
                    <need_hs>0</need_hs>
                    <top_port class_id_reference="25" object_id_reference="_83"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id="_95">
                    <type>0</type>
                    <name>fftStage_1_U0</name>
                    <ssdmobj_id>66</ssdmobj_id>
                  </inst>
                </item>
                <item class_id_reference="30" object_id="_96">
                  <port class_id_reference="25" object_id="_97">
                    <name>p_fftOutData_0_0_0_0_01</name>
                    <dir>1</dir>
                    <type>0</type>
                    <need_hs>0</need_hs>
                    <top_port class_id_reference="25" object_id_reference="_84"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id_reference="_95"/>
                </item>
                <item class_id_reference="30" object_id="_98">
                  <port class_id_reference="25" object_id="_99">
                    <name>p_fftOutData_0_1_0_0_0</name>
                    <dir>1</dir>
                    <type>0</type>
                    <need_hs>0</need_hs>
                    <top_port class_id_reference="25" object_id_reference="_85"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id_reference="_95"/>
                </item>
                <item class_id_reference="30" object_id="_100">
                  <port class_id_reference="25" object_id="_101">
                    <name>p_fftOutData_0_1_0_0_02</name>
                    <dir>1</dir>
                    <type>0</type>
                    <need_hs>0</need_hs>
                    <top_port class_id_reference="25" object_id_reference="_86"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id_reference="_95"/>
                </item>
              </pins>
              <in_source_fork>0</in_source_fork>
              <in_sink_join>1</in_sink_join>
              <flag_in_gui>0</flag_in_gui>
            </item>
          </process_list>
          <channel_list class_id="32" tracking_level="0" version="0">
            <count>2</count>
            <item_version>0</item_version>
            <item class_id="26" tracking_level="1" version="0" object_id="_102">
              <type>1</type>
              <name>fftOutData_local</name>
              <ssdmobj_id>56</ssdmobj_id>
              <ctype>0</ctype>
              <depth>8</depth>
              <bitwidth>128</bitwidth>
              <suggested_type>0</suggested_type>
              <suggested_depth>8</suggested_depth>
              <source class_id_reference="30" object_id="_103">
                <port class_id_reference="25" object_id="_104">
                  <name>in</name>
                  <dir>0</dir>
                  <type>3</type>
                  <need_hs>0</need_hs>
                  <top_port class_id="-1"/>
                  <chan class_id="-1"/>
                </port>
                <inst class_id_reference="31" object_id_reference="_90"/>
              </source>
              <sink class_id_reference="30" object_id="_105">
                <port class_id_reference="25" object_id="_106">
                  <name>out</name>
                  <dir>1</dir>
                  <type>3</type>
                  <need_hs>0</need_hs>
                  <top_port class_id="-1"/>
                  <chan class_id="-1"/>
                </port>
                <inst class_id_reference="31" object_id="_107">
                  <type>0</type>
                  <name>streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_U0</name>
                  <ssdmobj_id>65</ssdmobj_id>
                </inst>
              </sink>
            </item>
            <item class_id_reference="26" object_id="_108">
              <type>1</type>
              <name>fftOutData_local2</name>
              <ssdmobj_id>60</ssdmobj_id>
              <ctype>0</ctype>
              <depth>8</depth>
              <bitwidth>128</bitwidth>
              <suggested_type>0</suggested_type>
              <suggested_depth>8</suggested_depth>
              <source class_id_reference="30" object_id="_109">
                <port class_id_reference="25" object_id="_110">
                  <name>in</name>
                  <dir>0</dir>
                  <type>3</type>
                  <need_hs>0</need_hs>
                  <top_port class_id="-1"/>
                  <chan class_id="-1"/>
                </port>
                <inst class_id_reference="31" object_id_reference="_107"/>
              </source>
              <sink class_id_reference="30" object_id="_111">
                <port class_id_reference="25" object_id="_112">
                  <name>out</name>
                  <dir>1</dir>
                  <type>3</type>
                  <need_hs>0</need_hs>
                  <top_port class_id="-1"/>
                  <chan class_id="-1"/>
                </port>
                <inst class_id_reference="31" object_id_reference="_95"/>
              </sink>
            </item>
          </channel_list>
          <net_list class_id="33" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </net_list>
        </mDfPipe>
      </item>
    </cdfg_regions>
    <fsm class_id="34" tracking_level="1" version="0" object_id="_113">
      <states class_id="35" tracking_level="0" version="0">
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="1" version="0" object_id="_114">
          <id>1</id>
          <operations class_id="37" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="38" tracking_level="1" version="0" object_id="_115">
              <id>56</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_116">
              <id>60</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_117">
              <id>64</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_118">
          <id>2</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_119">
              <id>64</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_120">
          <id>3</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_121">
              <id>65</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_122">
          <id>4</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_123">
              <id>65</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_124">
          <id>5</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_125">
              <id>66</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_126">
          <id>6</id>
          <operations>
            <count>15</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_127">
              <id>49</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_128">
              <id>50</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_129">
              <id>51</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_130">
              <id>52</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_131">
              <id>53</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_132">
              <id>54</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_133">
              <id>55</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_134">
              <id>57</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_135">
              <id>58</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_136">
              <id>59</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_137">
              <id>61</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_138">
              <id>62</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_139">
              <id>63</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_140">
              <id>66</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
            <item class_id_reference="38" object_id="_141">
              <id>67</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="39" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="40" tracking_level="1" version="0" object_id="_142">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="41" tracking_level="0" version="0">
            <id>-1</id>
            <sop class_id="42" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="43" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_143">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_144">
          <inState>3</inState>
          <outState>4</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_145">
          <inState>4</inState>
          <outState>5</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_146">
          <inState>5</inState>
          <outState>6</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="44" tracking_level="1" version="0" object_id="_147">
      <dp_component_resource class_id="45" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="46" tracking_level="0" version="0">
          <first>fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_U0 (fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_s)</first>
          <second class_id="47" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="48" tracking_level="0" version="0">
              <first>BRAM</first>
              <second>0</second>
            </item>
            <item>
              <first>DSP</first>
              <second>4</second>
            </item>
            <item>
              <first>FF</first>
              <second>497</second>
            </item>
            <item>
              <first>LUT</first>
              <second>794</second>
            </item>
          </second>
        </item>
        <item>
          <first>fftStage_1_U0 (fftStage_1)</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>BRAM</first>
              <second>0</second>
            </item>
            <item>
              <first>DSP</first>
              <second>16</second>
            </item>
            <item>
              <first>FF</first>
              <second>5166</second>
            </item>
            <item>
              <first>LUT</first>
              <second>7078</second>
            </item>
            <item>
              <first>URAM</first>
              <second>0</second>
            </item>
          </second>
        </item>
        <item>
          <first>streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_U0 (streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_s)</first>
          <second>
            <count>2</count>
            <item_version>0</item_version>
            <item>
              <first>FF</first>
              <second>421</second>
            </item>
            <item>
              <first>LUT</first>
              <second>446</second>
            </item>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>ap_idle ( and ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>fftStage_1_U0_ap_start ( or ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_U0_ap_start ( or ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>fftOutData_local2_U</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Depth)</first>
              <second>8</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>128</second>
            </item>
            <item>
              <first>(2Size:D*B)</first>
              <second>1024</second>
            </item>
            <item>
              <first>FF</first>
              <second>99</second>
            </item>
            <item>
              <first>LUT</first>
              <second>66</second>
            </item>
          </second>
        </item>
        <item>
          <first>fftOutData_local_U</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Depth)</first>
              <second>8</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>128</second>
            </item>
            <item>
              <first>(2Size:D*B)</first>
              <second>1024</second>
            </item>
            <item>
              <first>FF</first>
              <second>99</second>
            </item>
            <item>
              <first>LUT</first>
              <second>66</second>
            </item>
          </second>
        </item>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>ap_sync_reg_fftStage_1_U0_ap_start</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_sync_reg_streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_U0_ap_start</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_U0</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>fftStage_1_U0</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_U0</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="49" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="50" tracking_level="0" version="0">
          <first>fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_U0 (fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>64</item>
          </second>
        </item>
        <item>
          <first>fftStage_1_U0 (fftStage_1)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>66</item>
          </second>
        </item>
        <item>
          <first>streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_U0 (streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>65</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_map>
      <dp_fifo_map>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>fftOutData_local2_U</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>87</item>
          </second>
        </item>
        <item>
          <first>fftOutData_local_U</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>77</item>
          </second>
        </item>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="51" tracking_level="0" version="0">
      <count>6</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>56</first>
        <second class_id="53" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>60</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>64</first>
        <second>
          <first>0</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>65</first>
        <second>
          <first>2</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>66</first>
        <second>
          <first>4</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>67</first>
        <second>
          <first>5</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="54" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="55" tracking_level="0" version="0">
        <first>68</first>
        <second class_id="56" tracking_level="0" version="0">
          <first>0</first>
          <second>5</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="57" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="58" tracking_level="1" version="0" object_id="_148">
        <region_name>fftStage</region_name>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>68</item>
        </basic_blocks>
        <nodes>
          <count>19</count>
          <item_version>0</item_version>
          <item>49</item>
          <item>50</item>
          <item>51</item>
          <item>52</item>
          <item>53</item>
          <item>54</item>
          <item>55</item>
          <item>56</item>
          <item>57</item>
          <item>58</item>
          <item>59</item>
          <item>60</item>
          <item>61</item>
          <item>62</item>
          <item>63</item>
          <item>64</item>
          <item>65</item>
          <item>66</item>
          <item>67</item>
        </nodes>
        <anchor_node>-1</anchor_node>
        <region_type>16</region_type>
        <interval>0</interval>
        <pipe_depth>0</pipe_depth>
        <mDBIIViolationVec class_id="59" tracking_level="0" version="0">
          <count>0</count>
          <item_version>0</item_version>
        </mDBIIViolationVec>
      </item>
    </regions>
    <dp_fu_nodes class_id="60" tracking_level="0" version="0">
      <count>5</count>
      <item_version>0</item_version>
      <item class_id="61" tracking_level="0" version="0">
        <first>142</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>56</item>
        </second>
      </item>
      <item>
        <first>146</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>60</item>
        </second>
      </item>
      <item>
        <first>150</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>64</item>
          <item>64</item>
        </second>
      </item>
      <item>
        <first>159</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>65</item>
          <item>65</item>
        </second>
      </item>
      <item>
        <first>181</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>66</item>
          <item>66</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="63" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="64" tracking_level="0" version="0">
        <first>fftOutData_local2_fu_146</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>60</item>
        </second>
      </item>
      <item>
        <first>fftOutData_local_fu_142</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>56</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>grp_fftStageKernelS2S_64_2_1_0_0_6_complex_ap_fixed_24_9_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_22_7_5_3_0_complex_ap_fixed_24_9_5_3_0_s_fu_150</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>64</item>
          <item>64</item>
        </second>
      </item>
      <item>
        <first>grp_fftStage_1_fu_181</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>66</item>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>grp_streamingDataCommutor_complex_ap_fixed_24_9_5_3_0_s_fu_159</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>65</item>
          <item>65</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="65" tracking_level="0" version="0">
      <count>19</count>
      <item_version>0</item_version>
      <item class_id="66" tracking_level="0" version="0">
        <first class_id="67" tracking_level="0" version="0">
          <first>control_delayline_Array</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>65</item>
        </second>
      </item>
      <item>
        <first>
          <first>control_delayline_Array_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>control_delayline_Array_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>control_delayline_Array_7</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>control_delayline_Array_9</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>65</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_10</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_13</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_14</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_19</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>65</item>
        </second>
      </item>
      <item>
        <first>
          <first>delayline_Array_9</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>twiddleObj_twiddleTable_M_imag_V</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>64</item>
        </second>
      </item>
      <item>
        <first>
          <first>twiddleObj_twiddleTable_M_imag_V_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>twiddleObj_twiddleTable_M_imag_V_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
      <item>
        <first>
          <first>twiddleObj_twiddleTable_M_imag_V_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>66</item>
        </second>
      </item>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>262</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>56</item>
        </second>
      </item>
      <item>
        <first>268</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>60</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>fftOutData_local2_reg_268</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>60</item>
        </second>
      </item>
      <item>
        <first>fftOutData_local_reg_262</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>56</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="68" tracking_level="0" version="0">
      <count>5</count>
      <item_version>0</item_version>
      <item class_id="69" tracking_level="0" version="0">
        <first>p_fftInData_reOrdered</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>64</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>p_fftOutData_0_0_0_0_0</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>66</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>p_fftOutData_0_0_0_0_01</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>66</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>p_fftOutData_0_1_0_0_0</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>66</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>p_fftOutData_0_1_0_0_02</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>66</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core>
      <count>5</count>
      <item_version>0</item_version>
      <item>
        <first>1</first>
        <second>
          <first>666</first>
          <second>9</second>
        </second>
      </item>
      <item>
        <first>2</first>
        <second>
          <first>1151</first>
          <second>7</second>
        </second>
      </item>
      <item>
        <first>3</first>
        <second>
          <first>1151</first>
          <second>7</second>
        </second>
      </item>
      <item>
        <first>4</first>
        <second>
          <first>1151</first>
          <second>7</second>
        </second>
      </item>
      <item>
        <first>5</first>
        <second>
          <first>1151</first>
          <second>7</second>
        </second>
      </item>
    </port2core>
    <node2core>
      <count>5</count>
      <item_version>0</item_version>
      <item>
        <first>56</first>
        <second>
          <first>1150</first>
          <second>9</second>
        </second>
      </item>
      <item>
        <first>60</first>
        <second>
          <first>1150</first>
          <second>9</second>
        </second>
      </item>
      <item>
        <first>64</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
      <item>
        <first>65</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
      <item>
        <first>66</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
    </node2core>
  </syndb>
</boost_serialization>
