-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity decoder_decoder_bit is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    y0300_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    y0300_empty_n : IN STD_LOGIC;
    y0300_read : OUT STD_LOGIC;
    y1301_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    y1301_empty_n : IN STD_LOGIC;
    y1301_read : OUT STD_LOGIC;
    output302_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    output302_full_n : IN STD_LOGIC;
    output302_write : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of decoder_decoder_bit is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal temp_trellis_survivor_V_i_q0 : STD_LOGIC_VECTOR (32 downto 0);
    signal temp_trellis_survivor_V_t_q0 : STD_LOGIC_VECTOR (32 downto 0);
    signal decoder_bit_Block_split148_proc3_U0_ap_start : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_ap_done : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_ap_continue : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_ap_idle : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_ap_ready : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_ce0 : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_we0 : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_d0 : STD_LOGIC_VECTOR (32 downto 0);
    signal decoder_bit_Block_split148_proc3_U0_y0300_read : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_y1301_read : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_best_branch_loc_channel : STD_LOGIC;
    signal best_branch_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_best_branch_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_best_branch_loc_channel : STD_LOGIC;
    signal ap_channel_done_temp_trellis_survivor_V : STD_LOGIC;
    signal decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_temp_trellis_survivor_V : STD_LOGIC := '0';
    signal ap_sync_channel_write_temp_trellis_survivor_V : STD_LOGIC;
    signal decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_start : STD_LOGIC;
    signal decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_done : STD_LOGIC;
    signal decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_continue : STD_LOGIC;
    signal decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_idle : STD_LOGIC;
    signal decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_ready : STD_LOGIC;
    signal decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_temp_trellis_survivor_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_temp_trellis_survivor_V_ce0 : STD_LOGIC;
    signal decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal best_branch_3_cast_loc_channel_full_n : STD_LOGIC;
    signal decoder_bit_Block_split223_proc_U0_ap_start : STD_LOGIC;
    signal decoder_bit_Block_split223_proc_U0_ap_done : STD_LOGIC;
    signal decoder_bit_Block_split223_proc_U0_ap_continue : STD_LOGIC;
    signal decoder_bit_Block_split223_proc_U0_ap_idle : STD_LOGIC;
    signal decoder_bit_Block_split223_proc_U0_ap_ready : STD_LOGIC;
    signal decoder_bit_Block_split223_proc_U0_output302_din : STD_LOGIC_VECTOR (0 downto 0);
    signal decoder_bit_Block_split223_proc_U0_output302_write : STD_LOGIC;
    signal temp_trellis_survivor_V_i_full_n : STD_LOGIC;
    signal temp_trellis_survivor_V_t_empty_n : STD_LOGIC;
    signal best_branch_loc_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal best_branch_loc_channel_empty_n : STD_LOGIC;
    signal best_branch_3_cast_loc_channel_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal best_branch_3_cast_loc_channel_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component decoder_decoder_bit_Block_split148_proc3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        temp_trellis_survivor_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        temp_trellis_survivor_V_ce0 : OUT STD_LOGIC;
        temp_trellis_survivor_V_we0 : OUT STD_LOGIC;
        temp_trellis_survivor_V_d0 : OUT STD_LOGIC_VECTOR (32 downto 0);
        y0300_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        y0300_empty_n : IN STD_LOGIC;
        y0300_read : OUT STD_LOGIC;
        y1301_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        y1301_empty_n : IN STD_LOGIC;
        y1301_read : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component decoder_decoder_bit_Loop_VITIS_LOOP_246_6_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        temp_trellis_survivor_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        temp_trellis_survivor_V_ce0 : OUT STD_LOGIC;
        temp_trellis_survivor_V_q0 : IN STD_LOGIC_VECTOR (32 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component decoder_decoder_bit_Block_split223_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (0 downto 0);
        output302_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        output302_full_n : IN STD_LOGIC;
        output302_write : OUT STD_LOGIC );
    end component;


    component decoder_decoder_bit_temp_trellis_survivor_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (32 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (32 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (32 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (32 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component decoder_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component decoder_fifo_w1_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    temp_trellis_survivor_V_U : component decoder_decoder_bit_temp_trellis_survivor_V
    generic map (
        DataWidth => 33,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_address0,
        i_ce0 => decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_ce0,
        i_we0 => decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_we0,
        i_d0 => decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_d0,
        i_q0 => temp_trellis_survivor_V_i_q0,
        t_address0 => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_temp_trellis_survivor_V_address0,
        t_ce0 => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_temp_trellis_survivor_V_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv33_0,
        t_q0 => temp_trellis_survivor_V_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => temp_trellis_survivor_V_i_full_n,
        i_write => ap_channel_done_temp_trellis_survivor_V,
        t_empty_n => temp_trellis_survivor_V_t_empty_n,
        t_read => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_ready);

    decoder_bit_Block_split148_proc3_U0 : component decoder_decoder_bit_Block_split148_proc3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => decoder_bit_Block_split148_proc3_U0_ap_start,
        ap_done => decoder_bit_Block_split148_proc3_U0_ap_done,
        ap_continue => decoder_bit_Block_split148_proc3_U0_ap_continue,
        ap_idle => decoder_bit_Block_split148_proc3_U0_ap_idle,
        ap_ready => decoder_bit_Block_split148_proc3_U0_ap_ready,
        temp_trellis_survivor_V_address0 => decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_address0,
        temp_trellis_survivor_V_ce0 => decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_ce0,
        temp_trellis_survivor_V_we0 => decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_we0,
        temp_trellis_survivor_V_d0 => decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_d0,
        y0300_dout => y0300_dout,
        y0300_empty_n => y0300_empty_n,
        y0300_read => decoder_bit_Block_split148_proc3_U0_y0300_read,
        y1301_dout => y1301_dout,
        y1301_empty_n => y1301_empty_n,
        y1301_read => decoder_bit_Block_split148_proc3_U0_y1301_read,
        ap_return => decoder_bit_Block_split148_proc3_U0_ap_return);

    decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0 : component decoder_decoder_bit_Loop_VITIS_LOOP_246_6_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_start,
        ap_done => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_done,
        ap_continue => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_continue,
        ap_idle => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_idle,
        ap_ready => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_ready,
        p_read => best_branch_loc_channel_dout,
        temp_trellis_survivor_V_address0 => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_temp_trellis_survivor_V_address0,
        temp_trellis_survivor_V_ce0 => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_temp_trellis_survivor_V_ce0,
        temp_trellis_survivor_V_q0 => temp_trellis_survivor_V_t_q0,
        ap_return => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_return);

    decoder_bit_Block_split223_proc_U0 : component decoder_decoder_bit_Block_split223_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => decoder_bit_Block_split223_proc_U0_ap_start,
        ap_done => decoder_bit_Block_split223_proc_U0_ap_done,
        ap_continue => decoder_bit_Block_split223_proc_U0_ap_continue,
        ap_idle => decoder_bit_Block_split223_proc_U0_ap_idle,
        ap_ready => decoder_bit_Block_split223_proc_U0_ap_ready,
        p_read => best_branch_3_cast_loc_channel_dout,
        output302_din => decoder_bit_Block_split223_proc_U0_output302_din,
        output302_full_n => output302_full_n,
        output302_write => decoder_bit_Block_split223_proc_U0_output302_write);

    best_branch_loc_channel_U : component decoder_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => decoder_bit_Block_split148_proc3_U0_ap_return,
        if_full_n => best_branch_loc_channel_full_n,
        if_write => ap_channel_done_best_branch_loc_channel,
        if_dout => best_branch_loc_channel_dout,
        if_empty_n => best_branch_loc_channel_empty_n,
        if_read => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_ready);

    best_branch_3_cast_loc_channel_U : component decoder_fifo_w1_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_return,
        if_full_n => best_branch_3_cast_loc_channel_full_n,
        if_write => decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_done,
        if_dout => best_branch_3_cast_loc_channel_dout,
        if_empty_n => best_branch_3_cast_loc_channel_empty_n,
        if_read => decoder_bit_Block_split223_proc_U0_ap_ready);





    ap_sync_reg_channel_write_best_branch_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_best_branch_loc_channel <= ap_const_logic_0;
            else
                if (((decoder_bit_Block_split148_proc3_U0_ap_done and decoder_bit_Block_split148_proc3_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_best_branch_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_best_branch_loc_channel <= ap_sync_channel_write_best_branch_loc_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_temp_trellis_survivor_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_temp_trellis_survivor_V <= ap_const_logic_0;
            else
                if (((decoder_bit_Block_split148_proc3_U0_ap_done and decoder_bit_Block_split148_proc3_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_temp_trellis_survivor_V <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_temp_trellis_survivor_V <= ap_sync_channel_write_temp_trellis_survivor_V;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_best_branch_loc_channel <= ((ap_sync_reg_channel_write_best_branch_loc_channel xor ap_const_logic_1) and decoder_bit_Block_split148_proc3_U0_ap_done);
    ap_channel_done_temp_trellis_survivor_V <= ((ap_sync_reg_channel_write_temp_trellis_survivor_V xor ap_const_logic_1) and decoder_bit_Block_split148_proc3_U0_ap_done);
    ap_done <= decoder_bit_Block_split223_proc_U0_ap_done;
    ap_idle <= ((best_branch_3_cast_loc_channel_empty_n xor ap_const_logic_1) and (best_branch_loc_channel_empty_n xor ap_const_logic_1) and (temp_trellis_survivor_V_t_empty_n xor ap_const_logic_1) and decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_idle and decoder_bit_Block_split223_proc_U0_ap_idle and decoder_bit_Block_split148_proc3_U0_ap_idle);
    ap_ready <= decoder_bit_Block_split148_proc3_U0_ap_ready;
    ap_sync_channel_write_best_branch_loc_channel <= ((best_branch_loc_channel_full_n and ap_channel_done_best_branch_loc_channel) or ap_sync_reg_channel_write_best_branch_loc_channel);
    ap_sync_channel_write_temp_trellis_survivor_V <= ((decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_full_n and ap_channel_done_temp_trellis_survivor_V) or ap_sync_reg_channel_write_temp_trellis_survivor_V);
    decoder_bit_Block_split148_proc3_U0_ap_continue <= (ap_sync_channel_write_temp_trellis_survivor_V and ap_sync_channel_write_best_branch_loc_channel);
    decoder_bit_Block_split148_proc3_U0_ap_start <= ap_start;
    decoder_bit_Block_split148_proc3_U0_temp_trellis_survivor_V_full_n <= temp_trellis_survivor_V_i_full_n;
    decoder_bit_Block_split223_proc_U0_ap_continue <= ap_continue;
    decoder_bit_Block_split223_proc_U0_ap_start <= best_branch_3_cast_loc_channel_empty_n;
    decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_continue <= best_branch_3_cast_loc_channel_full_n;
    decoder_bit_Loop_VITIS_LOOP_246_6_proc_U0_ap_start <= (temp_trellis_survivor_V_t_empty_n and best_branch_loc_channel_empty_n);
    output302_din <= decoder_bit_Block_split223_proc_U0_output302_din;
    output302_write <= decoder_bit_Block_split223_proc_U0_output302_write;
    y0300_read <= decoder_bit_Block_split148_proc3_U0_y0300_read;
    y1301_read <= decoder_bit_Block_split148_proc3_U0_y1301_read;
end behav;
