// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft_top1_fftStageKernelLastStageS2S_64_2_1_0_0_1_complex_ap_fixed_27_14_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_27_13_5_3_0_complex_ap_fixed_27_14_5_3_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        fftOutData_local2_dout,
        fftOutData_local2_empty_n,
        fftOutData_local2_read,
        fftOutData_local_din,
        fftOutData_local_full_n,
        fftOutData_local_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] fftOutData_local2_dout;
input   fftOutData_local2_empty_n;
output   fftOutData_local2_read;
output  [127:0] fftOutData_local_din;
input   fftOutData_local_full_n;
output   fftOutData_local_write;
output   start_out;
output   start_write;

reg ap_done;
reg ap_idle;
reg fftOutData_local2_read;
reg fftOutData_local_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [0:0] icmp_ln215_fu_311_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_nbreadreq_fu_82_p3;
reg    ap_block_state2_pp0_stage0_iter0;
reg   [0:0] tmp_reg_356;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    fftOutData_local2_blk_n;
wire    ap_block_pp0_stage0;
reg    fftOutData_local_blk_n;
reg   [31:0] iter1_reg_118;
reg   [25:0] bflyOutData_M_real_V_0_reg_360;
reg   [25:0] bflyOutData_M_imag_V_0_reg_365;
reg   [25:0] bflyOutData_M_real_V_1_reg_370;
reg   [25:0] trunc_ln717_s_reg_375;
wire   [31:0] iter_fu_295_p2;
reg   [31:0] iter_reg_380;
reg   [0:0] icmp_ln215_reg_385;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg   [31:0] ap_phi_mux_iter1_phi_fu_122_p6;
reg   [31:0] ap_phi_mux_iter_1_phi_fu_135_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_iter_1_reg_132;
wire   [31:0] iter_2_fu_142_p2;
reg    ap_block_pp0_stage0_01001;
wire   [26:0] X_of_ns_M_real_V_1_fu_163_p4;
wire   [26:0] X_of_ns_M_real_V_0_fu_149_p1;
wire   [26:0] X_of_ns_M_imag_V_1_fu_173_p4;
wire   [26:0] X_of_ns_M_imag_V_0_fu_153_p4;
wire   [26:0] add_ln712_fu_183_p2;
wire   [26:0] add_ln712_21_fu_189_p2;
wire   [39:0] shl_ln_fu_215_p3;
wire   [39:0] r_V_fu_223_p2;
wire   [39:0] shl_ln1171_6_fu_239_p3;
wire   [39:0] r_V_27_fu_247_p2;
wire   [26:0] real1_V_fu_229_p4;
wire   [26:0] imag2_V_fu_253_p4;
wire   [26:0] add_ln712_22_fu_263_p2;
wire   [26:0] add_ln712_23_fu_269_p2;
wire   [26:0] tmp_47_fu_301_p4;
wire  signed [26:0] sext_ln174_fu_323_p1;
wire  signed [26:0] sext_ln717_1_fu_320_p1;
wire   [31:0] zext_ln174_fu_326_p1;
wire  signed [26:0] sext_ln717_fu_317_p1;
wire   [121:0] tmp_4_fu_330_p7;
wire  signed [122:0] sext_ln174_1_fu_345_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_89;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln215_reg_385 == 1'd0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= real_start;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln215_reg_385 == 1'd1))) begin
        iter1_reg_118 <= iter_reg_380;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln215_reg_385 == 1'd0)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        iter1_reg_118 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_82_p3 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bflyOutData_M_imag_V_0_reg_365 <= {{add_ln712_21_fu_189_p2[26:1]}};
        bflyOutData_M_real_V_0_reg_360 <= {{add_ln712_fu_183_p2[26:1]}};
        bflyOutData_M_real_V_1_reg_370 <= {{add_ln712_22_fu_263_p2[26:1]}};
        trunc_ln717_s_reg_375 <= {{add_ln712_23_fu_269_p2[26:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln215_reg_385 <= icmp_ln215_fu_311_p2;
        tmp_reg_356 <= tmp_nbreadreq_fu_82_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        iter_reg_380 <= iter_fu_295_p2;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln215_reg_385 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_89)) begin
        if ((icmp_ln215_reg_385 == 1'd0)) begin
            ap_phi_mux_iter1_phi_fu_122_p6 = 32'd0;
        end else if ((icmp_ln215_reg_385 == 1'd1)) begin
            ap_phi_mux_iter1_phi_fu_122_p6 = iter_reg_380;
        end else begin
            ap_phi_mux_iter1_phi_fu_122_p6 = iter1_reg_118;
        end
    end else begin
        ap_phi_mux_iter1_phi_fu_122_p6 = iter1_reg_118;
    end
end

always @ (*) begin
    if ((tmp_nbreadreq_fu_82_p3 == 1'd0)) begin
        ap_phi_mux_iter_1_phi_fu_135_p4 = iter_2_fu_142_p2;
    end else if ((tmp_nbreadreq_fu_82_p3 == 1'd1)) begin
        ap_phi_mux_iter_1_phi_fu_135_p4 = ap_phi_mux_iter1_phi_fu_122_p6;
    end else begin
        ap_phi_mux_iter_1_phi_fu_135_p4 = ap_phi_reg_pp0_iter0_iter_1_reg_132;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_nbreadreq_fu_82_p3 == 1'd1) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fftOutData_local2_blk_n = fftOutData_local2_empty_n;
    end else begin
        fftOutData_local2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_82_p3 == 1'd1) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fftOutData_local2_read = 1'b1;
    end else begin
        fftOutData_local2_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_356 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fftOutData_local_blk_n = fftOutData_local_full_n;
    end else begin
        fftOutData_local_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_356 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fftOutData_local_write = 1'b1;
    end else begin
        fftOutData_local_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (icmp_ln215_fu_311_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_of_ns_M_imag_V_0_fu_153_p4 = {{fftOutData_local2_dout[58:32]}};

assign X_of_ns_M_imag_V_1_fu_173_p4 = {{fftOutData_local2_dout[122:96]}};

assign X_of_ns_M_real_V_0_fu_149_p1 = fftOutData_local2_dout[26:0];

assign X_of_ns_M_real_V_1_fu_163_p4 = {{fftOutData_local2_dout[90:64]}};

assign add_ln712_21_fu_189_p2 = (X_of_ns_M_imag_V_1_fu_173_p4 + X_of_ns_M_imag_V_0_fu_153_p4);

assign add_ln712_22_fu_263_p2 = (real1_V_fu_229_p4 + X_of_ns_M_real_V_0_fu_149_p1);

assign add_ln712_23_fu_269_p2 = (imag2_V_fu_253_p4 + X_of_ns_M_imag_V_0_fu_153_p4);

assign add_ln712_fu_183_p2 = (X_of_ns_M_real_V_1_fu_163_p4 + X_of_ns_M_real_V_0_fu_149_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_356 == 1'd1) & (fftOutData_local_full_n == 1'b0)) | ((tmp_nbreadreq_fu_82_p3 == 1'd1) & (fftOutData_local2_empty_n == 1'b0) & (real_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_356 == 1'd1) & (fftOutData_local_full_n == 1'b0)) | ((tmp_nbreadreq_fu_82_p3 == 1'd1) & (fftOutData_local2_empty_n == 1'b0) & (real_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_356 == 1'd1) & (fftOutData_local_full_n == 1'b0)) | ((tmp_nbreadreq_fu_82_p3 == 1'd1) & (fftOutData_local2_empty_n == 1'b0) & (real_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((tmp_nbreadreq_fu_82_p3 == 1'd1) & (fftOutData_local2_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((tmp_reg_356 == 1'd1) & (fftOutData_local_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_89 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = real_start;

assign ap_phi_reg_pp0_iter0_iter_1_reg_132 = 'bx;

assign ap_ready = internal_ap_ready;

assign fftOutData_local_din = $unsigned(sext_ln174_1_fu_345_p1);

assign icmp_ln215_fu_311_p2 = (($signed(tmp_47_fu_301_p4) < $signed(27'd1)) ? 1'b1 : 1'b0);

assign imag2_V_fu_253_p4 = {{r_V_27_fu_247_p2[39:13]}};

assign iter_2_fu_142_p2 = ($signed(ap_phi_mux_iter1_phi_fu_122_p6) + $signed(32'd4294967295));

assign iter_fu_295_p2 = (ap_phi_mux_iter_1_phi_fu_135_p4 + 32'd1);

assign r_V_27_fu_247_p2 = (40'd0 - shl_ln1171_6_fu_239_p3);

assign r_V_fu_223_p2 = (40'd0 - shl_ln_fu_215_p3);

assign real1_V_fu_229_p4 = {{r_V_fu_223_p2[39:13]}};

assign sext_ln174_1_fu_345_p1 = $signed(tmp_4_fu_330_p7);

assign sext_ln174_fu_323_p1 = $signed(bflyOutData_M_imag_V_0_reg_365);

assign sext_ln717_1_fu_320_p1 = $signed(bflyOutData_M_real_V_1_reg_370);

assign sext_ln717_fu_317_p1 = $signed(bflyOutData_M_real_V_0_reg_360);

assign shl_ln1171_6_fu_239_p3 = {{X_of_ns_M_imag_V_1_fu_173_p4}, {13'd0}};

assign shl_ln_fu_215_p3 = {{X_of_ns_M_real_V_1_fu_163_p4}, {13'd0}};

assign start_out = real_start;

assign tmp_47_fu_301_p4 = {{iter_fu_295_p2[31:5]}};

assign tmp_4_fu_330_p7 = {{{{{{trunc_ln717_s_reg_375}, {5'd0}}, {sext_ln717_1_fu_320_p1}}, {zext_ln174_fu_326_p1}}, {5'd0}}, {sext_ln717_fu_317_p1}};

assign tmp_nbreadreq_fu_82_p3 = fftOutData_local2_empty_n;

assign zext_ln174_fu_326_p1 = $unsigned(sext_ln174_fu_323_p1);

endmodule //fft_top1_fftStageKernelLastStageS2S_64_2_1_0_0_1_complex_ap_fixed_27_14_5_3_0_complex_ap_fixed_16_3_5_3_0_complex_ap_fixed_27_13_5_3_0_complex_ap_fixed_27_14_5_3_0_s
