-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_top0_streamingDataCommutor_complex_ap_fixed_22_7_5_3_0_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    temp_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    temp_empty_n : IN STD_LOGIC;
    temp_read : OUT STD_LOGIC;
    temp1_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    temp1_full_n : IN STD_LOGIC;
    temp1_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of fft_top0_streamingDataCommutor_complex_ap_fixed_22_7_5_3_0_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_55 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010101";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_75 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110101";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal icmp_ln231_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal fifo_has_next_sample_nbreadreq_fu_110_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal delay_line_stall_6_load_reg_525 : STD_LOGIC_VECTOR (0 downto 0);
    signal delay_line_stall_6_load_reg_525_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln297_reg_576 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifo_has_next_sample_reg_516 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifo_has_next_sample_reg_516_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op77_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal control_count_V_6 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal control_bits_V_6 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal pf_count_V_4 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal sample_in_read_count_V_6 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal delay_line_stall_6 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal delayline_Array_4_ce0 : STD_LOGIC;
    signal delayline_Array_4_we0 : STD_LOGIC;
    signal delayline_Array_4_q0 : STD_LOGIC_VECTOR (44 downto 0);
    signal control_delayline_Array_6_ce0 : STD_LOGIC;
    signal control_delayline_Array_6_we0 : STD_LOGIC;
    signal control_delayline_Array_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal delayline_Array_3_ce0 : STD_LOGIC;
    signal delayline_Array_3_we0 : STD_LOGIC;
    signal delayline_Array_3_q0 : STD_LOGIC_VECTOR (44 downto 0);
    signal temp_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal temp1_blk_n : STD_LOGIC;
    signal t17_reg_146 : STD_LOGIC_VECTOR (5 downto 0);
    signal t_fu_217_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal t_reg_520 : STD_LOGIC_VECTOR (5 downto 0);
    signal delay_line_stall_6_load_load_fu_223_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln145_fu_227_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal icmp_ln231_reg_552 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln231_reg_552_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln79_fu_421_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln79_reg_556 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln79_7_fu_429_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln79_7_reg_561 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln130_fu_465_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln130_reg_566 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln130_s_reg_571 : STD_LOGIC_VECTOR (21 downto 0);
    signal and_ln297_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_t17_phi_fu_150_p6 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter0_arrayidx_0_01_load_0_i365_reg_160 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx_0_01_load_0_i365_reg_160 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_phi_reg_pp0_iter0_arrayidx_0_11_load_0_i364_reg_171 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx_0_11_load_0_i364_reg_171 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_valid_0_reg_182 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_182 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206 : STD_LOGIC_VECTOR (21 downto 0);
    signal xor_ln251_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pf_count_V_4_load_load_fu_271_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln870_fu_303_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln256_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_s_fu_333_p4 : STD_LOGIC_VECTOR (44 downto 0);
    signal zext_ln66_fu_379_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_2_fu_445_p4 : STD_LOGIC_VECTOR (44 downto 0);
    signal temp_tagged_mux_chain_input_sample_M_real_V_1_fu_353_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal temp_tagged_mux_chain_input_sample_M_imag_V_1_fu_357_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal temp_tagged_mux_chain_input_valid_1_fu_367_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln79_fu_417_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln68_8_fu_409_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln68_7_fu_401_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln68_fu_393_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln79_8_fu_437_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_flag_fu_479_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln174_fu_493_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_496_p7 : STD_LOGIC_VECTOR (117 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_200 : BOOLEAN;
    signal ap_condition_84 : BOOLEAN;
    signal ap_condition_211 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component fft_top0_streamingDataCommutor_complex_ap_fixed_22_7_5_3_0_1_delayline_Array_4 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (44 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (44 downto 0) );
    end component;


    component fft_top0_streamingDataCommutor_complex_ap_fixed_22_7_5_3_0_1_control_delayline_Array_6 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    delayline_Array_4_U : component fft_top0_streamingDataCommutor_complex_ap_fixed_22_7_5_3_0_1_delayline_Array_4
    generic map (
        DataWidth => 45,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => delayline_Array_4_ce0,
        we0 => delayline_Array_4_we0,
        d0 => p_s_fu_333_p4,
        q0 => delayline_Array_4_q0);

    control_delayline_Array_6_U : component fft_top0_streamingDataCommutor_complex_ap_fixed_22_7_5_3_0_1_control_delayline_Array_6
    generic map (
        DataWidth => 32,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => control_delayline_Array_6_ce0,
        we0 => control_delayline_Array_6_we0,
        d0 => zext_ln66_fu_379_p1,
        q0 => control_delayline_Array_6_q0);

    delayline_Array_3_U : component fft_top0_streamingDataCommutor_complex_ap_fixed_22_7_5_3_0_1_delayline_Array_4
    generic map (
        DataWidth => 45,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv1_1,
        ce0 => delayline_Array_3_ce0,
        we0 => delayline_Array_3_we0,
        d0 => p_2_fu_445_p4,
        q0 => delayline_Array_3_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln231_reg_552_pp0_iter1_reg = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= real_start;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_arrayidx_0_01_load_0_i365_reg_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_84)) then
                if (((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_0) and (delay_line_stall_6_load_load_fu_223_p1 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx_0_01_load_0_i365_reg_160 <= ap_const_lv22_0;
                elsif ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx_0_01_load_0_i365_reg_160 <= temp_dout(85 downto 64);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx_0_01_load_0_i365_reg_160 <= ap_phi_reg_pp0_iter0_arrayidx_0_01_load_0_i365_reg_160;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_arrayidx_0_11_load_0_i364_reg_171_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_84)) then
                if (((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_0) and (delay_line_stall_6_load_load_fu_223_p1 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx_0_11_load_0_i364_reg_171 <= ap_const_lv22_0;
                elsif ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx_0_11_load_0_i364_reg_171 <= temp_dout(117 downto 96);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx_0_11_load_0_i364_reg_171 <= ap_phi_reg_pp0_iter0_arrayidx_0_11_load_0_i364_reg_171;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_84)) then
                if (((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_0) and (delay_line_stall_6_load_load_fu_223_p1 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206 <= ap_const_lv22_0;
                elsif ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206 <= temp_dout(53 downto 32);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206 <= ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_84)) then
                if (((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_0) and (delay_line_stall_6_load_load_fu_223_p1 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195 <= ap_const_lv22_0;
                elsif ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195 <= trunc_ln145_fu_227_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195 <= ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_84)) then
                if (((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_0) and (delay_line_stall_6_load_load_fu_223_p1 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_182 <= ap_const_lv1_0;
                elsif ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_182 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_182 <= ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_valid_0_reg_182;
                end if;
            end if; 
        end if;
    end process;

    pf_count_V_4_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_211)) then
                if ((pf_count_V_4_load_load_fu_271_p1 = ap_const_lv1_1)) then 
                    pf_count_V_4 <= ap_const_lv1_0;
                elsif ((pf_count_V_4_load_load_fu_271_p1 = ap_const_lv1_0)) then 
                    pf_count_V_4 <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    t17_reg_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln231_reg_552 = ap_const_lv1_0))) then 
                t17_reg_146 <= t_reg_520;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln231_reg_552 = ap_const_lv1_1)) or (not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                t17_reg_146 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((fifo_has_next_sample_reg_516 = ap_const_lv1_1) or (delay_line_stall_6_load_reg_525 = ap_const_lv1_0)))) then
                and_ln297_reg_576 <= and_ln297_fu_487_p2;
                lshr_ln130_s_reg_571 <= delayline_Array_3_q0(43 downto 22);
                select_ln79_7_reg_561 <= select_ln79_7_fu_429_p3;
                select_ln79_reg_556 <= select_ln79_fu_421_p3;
                trunc_ln130_reg_566 <= trunc_ln130_fu_465_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                control_bits_V_6 <= control_count_V_6;
                delay_line_stall_6 <= icmp_ln256_fu_309_p2;
                sample_in_read_count_V_6 <= add_ln870_fu_303_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (real_start = ap_const_logic_1) and (pf_count_V_4_load_load_fu_271_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                control_count_V_6 <= xor_ln251_fu_287_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                delay_line_stall_6_load_reg_525 <= delay_line_stall_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                delay_line_stall_6_load_reg_525_pp0_iter1_reg <= delay_line_stall_6_load_reg_525;
                fifo_has_next_sample_reg_516 <= fifo_has_next_sample_nbreadreq_fu_110_p3;
                fifo_has_next_sample_reg_516_pp0_iter1_reg <= fifo_has_next_sample_reg_516;
                icmp_ln231_reg_552 <= icmp_ln231_fu_327_p2;
                icmp_ln231_reg_552_pp0_iter1_reg <= icmp_ln231_reg_552;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                t_reg_520 <= t_fu_217_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_reset_idle_pp0 = ap_const_logic_0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln870_fu_303_p2 <= std_logic_vector(unsigned(sample_in_read_count_V_6) + unsigned(ap_const_lv5_1));
    and_ln297_fu_487_p2 <= (valid_flag_fu_479_p3 and select_ln79_8_fu_437_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(real_start, ap_done_reg, temp_empty_n, fifo_has_next_sample_nbreadreq_fu_110_p3, temp1_full_n, ap_predicate_op77_write_state4, ap_enable_reg_pp0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op77_write_state4 = ap_const_boolean_1) and (temp1_full_n = ap_const_logic_0)) or ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (temp_empty_n = ap_const_logic_0) and (real_start = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(real_start, ap_done_reg, temp_empty_n, fifo_has_next_sample_nbreadreq_fu_110_p3, temp1_full_n, ap_predicate_op77_write_state4, ap_enable_reg_pp0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op77_write_state4 = ap_const_boolean_1) and (temp1_full_n = ap_const_logic_0)) or ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (temp_empty_n = ap_const_logic_0) and (real_start = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(real_start, ap_done_reg, temp_empty_n, fifo_has_next_sample_nbreadreq_fu_110_p3, temp1_full_n, ap_predicate_op77_write_state4, ap_enable_reg_pp0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op77_write_state4 = ap_const_boolean_1) and (temp1_full_n = ap_const_logic_0)) or ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (temp_empty_n = ap_const_logic_0) and (real_start = ap_const_logic_1)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(temp_empty_n, fifo_has_next_sample_nbreadreq_fu_110_p3)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (temp_empty_n = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter2_assign_proc : process(temp1_full_n, ap_predicate_op77_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter2 <= ((ap_predicate_op77_write_state4 = ap_const_boolean_1) and (temp1_full_n = ap_const_logic_0));
    end process;


    ap_condition_200_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_condition_200 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_211_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, fifo_has_next_sample_nbreadreq_fu_110_p3, ap_block_pp0_stage0_11001)
    begin
                ap_condition_211 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_84_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_84 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln231_reg_552_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln231_reg_552_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= real_start;

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_t17_phi_fu_150_p6_assign_proc : process(t17_reg_146, t_reg_520, icmp_ln231_reg_552, ap_condition_200)
    begin
        if ((ap_const_boolean_1 = ap_condition_200)) then
            if ((icmp_ln231_reg_552 = ap_const_lv1_1)) then 
                ap_phi_mux_t17_phi_fu_150_p6 <= ap_const_lv6_0;
            elsif ((icmp_ln231_reg_552 = ap_const_lv1_0)) then 
                ap_phi_mux_t17_phi_fu_150_p6 <= t_reg_520;
            else 
                ap_phi_mux_t17_phi_fu_150_p6 <= t17_reg_146;
            end if;
        else 
            ap_phi_mux_t17_phi_fu_150_p6 <= t17_reg_146;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_arrayidx_0_01_load_0_i365_reg_160 <= "XXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_arrayidx_0_11_load_0_i364_reg_171 <= "XXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206 <= "XXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195 <= "XXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_valid_0_reg_182 <= "X";

    ap_predicate_op77_write_state4_assign_proc : process(delay_line_stall_6_load_reg_525_pp0_iter1_reg, and_ln297_reg_576, fifo_has_next_sample_reg_516_pp0_iter1_reg)
    begin
                ap_predicate_op77_write_state4 <= (((fifo_has_next_sample_reg_516_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln297_reg_576)) or ((delay_line_stall_6_load_reg_525_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln297_reg_576)));
    end process;

    ap_ready <= internal_ap_ready;

    ap_reset_idle_pp0_assign_proc : process(real_start, ap_idle_pp0_0to1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    control_delayline_Array_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, delay_line_stall_6_load_reg_525, fifo_has_next_sample_reg_516, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((fifo_has_next_sample_reg_516 = ap_const_lv1_1) or (delay_line_stall_6_load_reg_525 = ap_const_lv1_0)))) then 
            control_delayline_Array_6_ce0 <= ap_const_logic_1;
        else 
            control_delayline_Array_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    control_delayline_Array_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, delay_line_stall_6_load_reg_525, fifo_has_next_sample_reg_516, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((fifo_has_next_sample_reg_516 = ap_const_lv1_1) or (delay_line_stall_6_load_reg_525 = ap_const_lv1_0)))) then 
            control_delayline_Array_6_we0 <= ap_const_logic_1;
        else 
            control_delayline_Array_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    delay_line_stall_6_load_load_fu_223_p1 <= delay_line_stall_6;

    delayline_Array_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, delay_line_stall_6_load_reg_525, fifo_has_next_sample_reg_516, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((fifo_has_next_sample_reg_516 = ap_const_lv1_1) or (delay_line_stall_6_load_reg_525 = ap_const_lv1_0)))) then 
            delayline_Array_3_ce0 <= ap_const_logic_1;
        else 
            delayline_Array_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    delayline_Array_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, delay_line_stall_6_load_reg_525, fifo_has_next_sample_reg_516, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((fifo_has_next_sample_reg_516 = ap_const_lv1_1) or (delay_line_stall_6_load_reg_525 = ap_const_lv1_0)))) then 
            delayline_Array_3_we0 <= ap_const_logic_1;
        else 
            delayline_Array_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    delayline_Array_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, delay_line_stall_6_load_reg_525, fifo_has_next_sample_reg_516, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((fifo_has_next_sample_reg_516 = ap_const_lv1_1) or (delay_line_stall_6_load_reg_525 = ap_const_lv1_0)))) then 
            delayline_Array_4_ce0 <= ap_const_logic_1;
        else 
            delayline_Array_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    delayline_Array_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, delay_line_stall_6_load_reg_525, fifo_has_next_sample_reg_516, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((fifo_has_next_sample_reg_516 = ap_const_lv1_1) or (delay_line_stall_6_load_reg_525 = ap_const_lv1_0)))) then 
            delayline_Array_4_we0 <= ap_const_logic_1;
        else 
            delayline_Array_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fifo_has_next_sample_nbreadreq_fu_110_p3 <= (0=>(temp_empty_n), others=>'-');
    icmp_ln231_fu_327_p2 <= "1" when (ap_phi_mux_t17_phi_fu_150_p6 = ap_const_lv6_23) else "0";
    icmp_ln256_fu_309_p2 <= "0" when (sample_in_read_count_V_6 = ap_const_lv5_1F) else "1";

    internal_ap_ready_assign_proc : process(real_start, icmp_ln231_fu_327_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (real_start = ap_const_logic_1) and (icmp_ln231_fu_327_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    p_2_fu_445_p4 <= ((select_ln68_8_fu_409_p3 & select_ln68_7_fu_401_p3) & select_ln68_fu_393_p3);
    p_s_fu_333_p4 <= ((ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_182 & ap_phi_reg_pp0_iter1_arrayidx_0_11_load_0_i364_reg_171) & ap_phi_reg_pp0_iter1_arrayidx_0_01_load_0_i365_reg_160);
    pf_count_V_4_load_load_fu_271_p1 <= pf_count_V_4;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln68_7_fu_401_p3 <= 
        temp_tagged_mux_chain_input_sample_M_imag_V_1_fu_357_p4 when (control_bits_V_6(0) = '1') else 
        ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206;
    select_ln68_8_fu_409_p3 <= 
        temp_tagged_mux_chain_input_valid_1_fu_367_p3 when (control_bits_V_6(0) = '1') else 
        ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_182;
    select_ln68_fu_393_p3 <= 
        temp_tagged_mux_chain_input_sample_M_real_V_1_fu_353_p1 when (control_bits_V_6(0) = '1') else 
        ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195;
    select_ln79_7_fu_429_p3 <= 
        temp_tagged_mux_chain_input_sample_M_imag_V_1_fu_357_p4 when (trunc_ln79_fu_417_p1(0) = '1') else 
        ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_206;
    select_ln79_8_fu_437_p3 <= 
        temp_tagged_mux_chain_input_valid_1_fu_367_p3 when (trunc_ln79_fu_417_p1(0) = '1') else 
        ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_182;
    select_ln79_fu_421_p3 <= 
        temp_tagged_mux_chain_input_sample_M_real_V_1_fu_353_p1 when (trunc_ln79_fu_417_p1(0) = '1') else 
        ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_195;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    t_fu_217_p2 <= std_logic_vector(unsigned(ap_phi_mux_t17_phi_fu_150_p6) + unsigned(ap_const_lv6_1));

    temp1_blk_n_assign_proc : process(temp1_full_n, ap_predicate_op77_write_state4, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op77_write_state4 = ap_const_boolean_1))) then 
            temp1_blk_n <= temp1_full_n;
        else 
            temp1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    temp1_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_496_p7),128));

    temp1_write_assign_proc : process(ap_predicate_op77_write_state4, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op77_write_state4 = ap_const_boolean_1))) then 
            temp1_write <= ap_const_logic_1;
        else 
            temp1_write <= ap_const_logic_0;
        end if; 
    end process;


    temp_blk_n_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, temp_empty_n, fifo_has_next_sample_nbreadreq_fu_110_p3, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_blk_n <= temp_empty_n;
        else 
            temp_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    temp_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, fifo_has_next_sample_nbreadreq_fu_110_p3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fifo_has_next_sample_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_read <= ap_const_logic_1;
        else 
            temp_read <= ap_const_logic_0;
        end if; 
    end process;

    temp_tagged_mux_chain_input_sample_M_imag_V_1_fu_357_p4 <= delayline_Array_4_q0(43 downto 22);
    temp_tagged_mux_chain_input_sample_M_real_V_1_fu_353_p1 <= delayline_Array_4_q0(22 - 1 downto 0);
    temp_tagged_mux_chain_input_valid_1_fu_367_p3 <= delayline_Array_4_q0(44 downto 44);
    tmp_fu_496_p7 <= (((((select_ln79_7_reg_561 & ap_const_lv10_0) & select_ln79_reg_556) & zext_ln174_fu_493_p1) & ap_const_lv10_0) & trunc_ln130_reg_566);
    trunc_ln130_fu_465_p1 <= delayline_Array_3_q0(22 - 1 downto 0);
    trunc_ln145_fu_227_p1 <= temp_dout(22 - 1 downto 0);
    trunc_ln79_fu_417_p1 <= control_delayline_Array_6_q0(1 - 1 downto 0);
    valid_flag_fu_479_p3 <= delayline_Array_3_q0(44 downto 44);
    xor_ln251_fu_287_p2 <= (control_count_V_6 xor ap_const_lv1_1);
    zext_ln174_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln130_s_reg_571),32));
    zext_ln66_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(control_bits_V_6),32));
end behav;
